-- +goose Up

CREATE TABLE country (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `iso2` varchar(5) NOT NULL,
  `iso3` varchar(5) NOT NULL,
  `callcode` varchar(5) NOT NULL,
  `name` varchar(100) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO country (iso2, iso3, callcode, name) VALUES ('AF', 'AFX', '+1', 'Afghanistan'),
('AX', 'AXX', '+2', 'Åland Islands'),
('AL', 'ALX', '+3', 'Albania'),
('DZ', 'DZX', '+4', 'Algeria'),
('AS', 'ASX', '+5', 'American Samoa'),
('AD', 'ADX', '+6', 'Andorra'),
('AO', 'AOX', '+7', 'Angola'),
('AI', 'AIX', '+8', 'Anguilla'),
('AG', 'AGX', '+9', 'Antigua & Barbuda'),
('AR', 'ARX', '+10', 'Argentina'),
('AM', 'AMX', '+11', 'Armenia'),
('AW', 'AWX', '+12', 'Aruba'),
('AC', 'ACX', '+13', 'Ascension Island'),
('AU', 'AUX', '+14', 'Australia'),
('AT', 'ATX', '+15', 'Austria'),
('AZ', 'AZX', '+16', 'Azerbaijan'),
('BS', 'BSX', '+17', 'Bahamas'),
('BH', 'BHX', '+18', 'Bahrain'),
('BD', 'BDX', '+19', 'Bangladesh'),
('BB', 'BBX', '+20', 'Barbados'),
('BY', 'BYX', '+21', 'Belarus'),
('BE', 'BEX', '+22', 'Belgium'),
('BZ', 'BZX', '+23', 'Belize'),
('BJ', 'BJX', '+24', 'Benin'),
('BM', 'BMX', '+25', 'Bermuda'),
('BT', 'BTX', '+26', 'Bhutan'),
('BO', 'BOX', '+27', 'Bolivia'),
('BA', 'BAX', '+28', 'Bosnia & Herzegovina'),
('BW', 'BWX', '+29', 'Botswana'),
('BR', 'BRX', '+30', 'Brazil'),
('IO', 'IOX', '+31', 'British Indian Ocean Territory'),
('VG', 'VGX', '+32', 'British Virgin Islands'),
('BN', 'BNX', '+33', 'Brunei'),
('BG', 'BGX', '+34', 'Bulgaria'),
('BF', 'BFX', '+35', 'Burkina Faso'),
('BI', 'BIX', '+36', 'Burundi'),
('KH', 'KHX', '+37', 'Cambodia'),
('CM', 'CMX', '+38', 'Cameroon'),
('CA', 'CAX', '+39', 'Canada'),
('CV', 'CVX', '+40', 'Cape Verde'),
('BQ', 'BQX', '+41', 'Caribbean Netherlands'),
('KY', 'KYX', '+42', 'Cayman Islands'),
('CF', 'CFX', '+43', 'Central African Republic'),
('TD', 'TDX', '+44', 'Chad'),
('CL', 'CLX', '+45', 'Chile'),
('CN', 'CNX', '+46', 'China'),
('CX', 'CXX', '+47', 'Christmas Island'),
('CC', 'CCX', '+48', 'Cocos (Keeling) Islands'),
('CO', 'COX', '+49', 'Colombia'),
('KM', 'KMX', '+50', 'Comoros'),
('CG', 'CGX', '+51', 'Congo - Brazzaville'),
('CD', 'CDX', '+52', 'Congo - Kinshasa'),
('CK', 'CKX', '+53', 'Cook Islands'),
('CR', 'CRX', '+54', 'Costa Rica'),
('CI', 'CIX', '+55', 'Côte d’Ivoire'),
('HR', 'HRX', '+56', 'Croatia'),
('CU', 'CUX', '+57', 'Cuba'),
('CW', 'CWX', '+58', 'Curaçao'),
('CY', 'CYX', '+59', 'Cyprus'),
('CZ', 'CZX', '+60', 'Czechia'),
('DK', 'DKX', '+61', 'Denmark'),
('DJ', 'DJX', '+62', 'Djibouti'),
('DM', 'DMX', '+63', 'Dominica'),
('DO', 'DOX', '+64', 'Dominican Republic'),
('EC', 'ECX', '+65', 'Ecuador'),
('EG', 'EGX', '+66', 'Egypt'),
('SV', 'SVX', '+67', 'El Salvador'),
('GQ', 'GQX', '+68', 'Equatorial Guinea'),
('ER', 'ERX', '+69', 'Eritrea'),
('EE', 'EEX', '+70', 'Estonia'),
('SZ', 'SZX', '+71', 'Eswatini'),
('ET', 'ETX', '+72', 'Ethiopia'),
('FK', 'FKX', '+73', 'Falkland Islands'),
('FO', 'FOX', '+74', 'Faroe Islands'),
('FJ', 'FJX', '+75', 'Fiji'),
('FI', 'FIX', '+76', 'Finland'),
('FR', 'FRX', '+77', 'France'),
('GF', 'GFX', '+78', 'French Guiana'),
('PF', 'PFX', '+79', 'French Polynesia'),
('GA', 'GAX', '+80', 'Gabon'),
('GM', 'GMX', '+81', 'Gambia'),
('GE', 'GEX', '+82', 'Georgia'),
('DE', 'DEX', '+83', 'Germany'),
('GH', 'GHX', '+84', 'Ghana'),
('GI', 'GIX', '+85', 'Gibraltar'),
('GR', 'GRX', '+86', 'Greece'),
('GL', 'GLX', '+87', 'Greenland'),
('GD', 'GDX', '+88', 'Grenada'),
('GP', 'GPX', '+89', 'Guadeloupe'),
('GU', 'GUX', '+90', 'Guam'),
('GT', 'GTX', '+91', 'Guatemala'),
('GG', 'GGX', '+92', 'Guernsey'),
('GN', 'GNX', '+93', 'Guinea'),
('GW', 'GWX', '+94', 'Guinea-Bissau'),
('GY', 'GYX', '+95', 'Guyana'),
('HT', 'HTX', '+96', 'Haiti'),
('HN', 'HNX', '+97', 'Honduras'),
('HK', 'HKX', '+98', 'Hong Kong SAR China'),
('HU', 'HUX', '+99', 'Hungary'),
('IS', 'ISX', '+100', 'Iceland'),
('IN', 'INX', '+101', 'India'),
('ID', 'IDX', '+102', 'Indonesia'),
('IR', 'IRX', '+103', 'Iran'),
('IQ', 'IQX', '+104', 'Iraq'),
('IE', 'IEX', '+105', 'Ireland'),
('IM', 'IMX', '+106', 'Isle of Man'),
('IL', 'ILX', '+107', 'Israel'),
('IT', 'ITX', '+108', 'Italy'),
('JM', 'JMX', '+109', 'Jamaica'),
('JP', 'JPX', '+110', 'Japan'),
('JE', 'JEX', '+111', 'Jersey'),
('JO', 'JOX', '+112', 'Jordan'),
('KZ', 'KZX', '+113', 'Kazakhstan'),
('KE', 'KEX', '+114', 'Kenya'),
('KI', 'KIX', '+115', 'Kiribati'),
('XK', 'XKX', '+116', 'Kosovo'),
('KW', 'KWX', '+117', 'Kuwait'),
('KG', 'KGX', '+118', 'Kyrgyzstan'),
('LA', 'LAX', '+119', 'Laos'),
('LV', 'LVX', '+120', 'Latvia'),
('LB', 'LBX', '+121', 'Lebanon'),
('LS', 'LSX', '+122', 'Lesotho'),
('LR', 'LRX', '+123', 'Liberia'),
('LY', 'LYX', '+124', 'Libya'),
('LI', 'LIX', '+125', 'Liechtenstein'),
('LT', 'LTX', '+126', 'Lithuania'),
('LU', 'LUX', '+127', 'Luxembourg'),
('MO', 'MOX', '+128', 'Macao SAR China'),
('MG', 'MGX', '+129', 'Madagascar'),
('MW', 'MWX', '+130', 'Malawi'),
('MY', 'MYX', '+131', 'Malaysia'),
('MV', 'MVX', '+132', 'Maldives'),
('ML', 'MLX', '+133', 'Mali'),
('MT', 'MTX', '+134', 'Malta'),
('MH', 'MHX', '+135', 'Marshall Islands'),
('MQ', 'MQX', '+136', 'Martinique'),
('MR', 'MRX', '+137', 'Mauritania'),
('MU', 'MUX', '+138', 'Mauritius'),
('YT', 'YTX', '+139', 'Mayotte'),
('MX', 'MXX', '+140', 'Mexico'),
('FM', 'FMX', '+141', 'Micronesia'),
('MD', 'MDX', '+142', 'Moldova'),
('MC', 'MCX', '+143', 'Monaco'),
('MN', 'MNX', '+144', 'Mongolia'),
('ME', 'MEX', '+145', 'Montenegro'),
('MS', 'MSX', '+146', 'Montserrat'),
('MA', 'MAX', '+147', 'Morocco'),
('MZ', 'MZX', '+148', 'Mozambique'),
('MM', 'MMX', '+149', 'Myanmar (Burma)'),
('NA', 'NAX', '+150', 'Namibia'),
('NR', 'NRX', '+151', 'Nauru'),
('NP', 'NPX', '+152', 'Nepal'),
('NL', 'NLX', '+153', 'Netherlands'),
('NC', 'NCX', '+154', 'New Caledonia'),
('NZ', 'NZX', '+155', 'New Zealand'),
('NI', 'NIX', '+156', 'Nicaragua'),
('NE', 'NEX', '+157', 'Niger'),
('NG', 'NGX', '+158', 'Nigeria'),
('NU', 'NUX', '+159', 'Niue'),
('NF', 'NFX', '+160', 'Norfolk Island'),
('KP', 'KPX', '+161', 'North Korea'),
('MK', 'MKX', '+162', 'North Macedonia'),
('MP', 'MPX', '+163', 'Northern Mariana Islands'),
('NO', 'NOX', '+164', 'Norway'),
('OM', 'OMX', '+165', 'Oman'),
('PK', 'PKX', '+166', 'Pakistan'),
('PW', 'PWX', '+167', 'Palau'),
('PS', 'PSX', '+168', 'Palestinian Territories'),
('PA', 'PAX', '+169', 'Panama'),
('PG', 'PGX', '+170', 'Papua New Guinea'),
('PY', 'PYX', '+171', 'Paraguay'),
('PE', 'PEX', '+172', 'Peru'),
('PH', 'PHX', '+173', 'Philippines'),
('PL', 'PLX', '+174', 'Poland'),
('PT', 'PTX', '+175', 'Portugal'),
('PR', 'PRX', '+176', 'Puerto Rico'),
('QA', 'QAX', '+177', 'Qatar'),
('RE', 'REX', '+178', 'Réunion'),
('RO', 'ROX', '+179', 'Romania'),
('RU', 'RUX', '+180', 'Russia'),
('RW', 'RWX', '+181', 'Rwanda'),
('WS', 'WSX', '+182', 'Samoa'),
('SM', 'SMX', '+183', 'San Marino'),
('ST', 'STX', '+184', 'São Tomé & Príncipe'),
('SA', 'SAX', '+185', 'Saudi Arabia'),
('SN', 'SNX', '+186', 'Senegal'),
('RS', 'RSX', '+187', 'Serbia'),
('SC', 'SCX', '+188', 'Seychelles'),
('SL', 'SLX', '+189', 'Sierra Leone'),
('SG', 'SGX', '+190', 'Singapore'),
('SX', 'SXX', '+191', 'Sint Maarten'),
('SK', 'SKX', '+192', 'Slovakia'),
('SI', 'SIX', '+193', 'Slovenia'),
('SB', 'SBX', '+194', 'Solomon Islands'),
('SO', 'SOX', '+195', 'Somalia'),
('ZA', 'ZAX', '+196', 'South Africa'),
('KR', 'KRX', '+197', 'South Korea'),
('SS', 'SSX', '+198', 'South Sudan'),
('ES', 'ESX', '+199', 'Spain'),
('LK', 'LKX', '+200', 'Sri Lanka'),
('BL', 'BLX', '+201', 'St. Barthélemy'),
('SH', 'SHX', '+202', 'St. Helena'),
('KN', 'KNX', '+203', 'St. Kitts & Nevis'),
('LC', 'LCX', '+204', 'St. Lucia'),
('MF', 'MFX', '+205', 'St. Martin'),
('PM', 'PMX', '+206', 'St. Pierre & Miquelon'),
('VC', 'VCX', '+207', 'St. Vincent & Grenadines'),
('SD', 'SDX', '+208', 'Sudan'),
('SR', 'SRX', '+209', 'Suriname'),
('SJ', 'SJX', '+210', 'Svalbard & Jan Mayen'),
('SE', 'SEX', '+211', 'Sweden'),
('CH', 'CHX', '+212', 'Switzerland'),
('SY', 'SYX', '+213', 'Syria'),
('TW', 'TWX', '+214', 'Taiwan'),
('TJ', 'TJX', '+215', 'Tajikistan'),
('TZ', 'TZX', '+216', 'Tanzania'),
('TH', 'THX', '+217', 'Thailand'),
('TL', 'TLX', '+218', 'Timor-Leste'),
('TG', 'TGX', '+219', 'Togo'),
('TK', 'TKX', '+220', 'Tokelau'),
('TO', 'TOX', '+221', 'Tonga'),
('TT', 'TTX', '+222', 'Trinidad & Tobago'),
('TA', 'TAX', '+223', 'Tristan da Cunha'),
('TN', 'TNX', '+224', 'Tunisia'),
('TR', 'TRX', '+225', 'Turkey'),
('TM', 'TMX', '+226', 'Turkmenistan'),
('TC', 'TCX', '+227', 'Turks & Caicos Islands'),
('TV', 'TVX', '+228', 'Tuvalu'),
('VI', 'VIX', '+229', 'U.S. Virgin Islands'),
('UG', 'UGX', '+230', 'Uganda'),
('UA', 'UAX', '+231', 'Ukraine'),
('AE', 'AEX', '+232', 'United Arab Emirates'),
('GB', 'GBX', '+233', 'United Kingdom'),
('US', 'USX', '+234', 'United States'),
('UY', 'UYX', '+235', 'Uruguay'),
('UZ', 'UZX', '+236', 'Uzbekistan'),
('VU', 'VUX', '+237', 'Vanuatu'),
('VA', 'VAX', '+238', 'Vatican City'),
('VE', 'VEX', '+239', 'Venezuela'),
('VN', 'VNX', '+240', 'Vietnam'),
('WF', 'WFX', '+241', 'Wallis & Futuna'),
('EH', 'EHX', '+242', 'Western Sahara'),
('YE', 'YEX', '+243', 'Yemen'),
('ZM', 'ZMX', '+244', 'Zambia'),
('ZW', 'ZWX', '+245', 'Zimbabwe');

-- +goose Down

DROP TABLE country;